# Generated by Django 4.1.7 on 2023-04-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_follow_unique_together_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_dislike',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
