# Generated by Django 4.1.7 on 2023-04-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_like_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_dislike',
            field=models.CharField(choices=[('Li', 'Like'), ('Di', 'Dislike'), ('No', 'Nolike')], default='No', max_length=2),
        ),
    ]
