# Generated by Django 4.1.7 on 2023-04-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_like_like_dislike_like_dislike_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='like_dislike',
            field=models.CharField(choices=[('Li', 'Like'), ('Di', 'Dislike'), ('No', 'Nolike')], default='No', max_length=2),
        ),
    ]
