# Generated by Django 4.1.7 on 2023-04-07 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_like_dislike_remove_like_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=1000)),
                ('about', models.CharField(blank=True, max_length=1000)),
                ('date_of_birth', models.DateTimeField(blank=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
