# Generated by Django 4.1.7 on 2023-04-07 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_rename_name_userinformation_userinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
