# Generated by Django 4.1.7 on 2023-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_userinformation_userinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
